package vn.com.vti.springexam.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.com.vti.springexam.entity.MemberCard;
import vn.com.vti.springexam.entity.MemberCardExample;
import vn.com.vti.springexam.entity.MemberCardKey;

public interface MemberCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    long countByExample(MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    int deleteByExample(MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    int deleteByPrimaryKey(MemberCardKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    int insert(MemberCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    int insertSelective(MemberCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    List<MemberCard> selectByExample(MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    MemberCard selectByPrimaryKey(MemberCardKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    int updateByExampleSelective(@Param("record") MemberCard record, @Param("example") MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    int updateByExample(@Param("record") MemberCard record, @Param("example") MemberCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    int updateByPrimaryKeySelective(MemberCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_card
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    int updateByPrimaryKey(MemberCard record);
}