package vn.com.vti.springexam.entity;

import java.util.Date;

public class Infrastructure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infrastructure.ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infrastructure.NAME
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infrastructure.REGIST_DATE
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    private Date registDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infrastructure.ID
     *
     * @return the value of infrastructure.ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infrastructure.ID
     *
     * @param id the value for infrastructure.ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infrastructure.NAME
     *
     * @return the value of infrastructure.NAME
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infrastructure.NAME
     *
     * @param name the value for infrastructure.NAME
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infrastructure.REGIST_DATE
     *
     * @return the value of infrastructure.REGIST_DATE
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infrastructure.REGIST_DATE
     *
     * @param registDate the value for infrastructure.REGIST_DATE
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }
}