package vn.com.vti.springexam.entity;

public class MemberCard extends MemberCardKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.card_company_id
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    private String cardCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.card_number
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    private String cardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.expire_year
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    private String expireYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.expire_month
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    private String expireMonth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.card_company_id
     *
     * @return the value of member_card.card_company_id
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    public String getCardCompanyId() {
        return cardCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.card_company_id
     *
     * @param cardCompanyId the value for member_card.card_company_id
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    public void setCardCompanyId(String cardCompanyId) {
        this.cardCompanyId = cardCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.card_number
     *
     * @return the value of member_card.card_number
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.card_number
     *
     * @param cardNumber the value for member_card.card_number
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.expire_year
     *
     * @return the value of member_card.expire_year
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    public String getExpireYear() {
        return expireYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.expire_year
     *
     * @param expireYear the value for member_card.expire_year
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    public void setExpireYear(String expireYear) {
        this.expireYear = expireYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.expire_month
     *
     * @return the value of member_card.expire_month
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    public String getExpireMonth() {
        return expireMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.expire_month
     *
     * @param expireMonth the value for member_card.expire_month
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    public void setExpireMonth(String expireMonth) {
        this.expireMonth = expireMonth;
    }
}