package vn.com.vti.springexam.entity;

public class MemberCardKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.member_id
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_card.member_card_id
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    private Integer memberCardId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.member_id
     *
     * @return the value of member_card.member_id
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.member_id
     *
     * @param memberId the value for member_card.member_id
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_card.member_card_id
     *
     * @return the value of member_card.member_card_id
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    public Integer getMemberCardId() {
        return memberCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_card.member_card_id
     *
     * @param memberCardId the value for member_card.member_card_id
     *
     * @mbg.generated Sat Sep 10 14:28:05 JST 2022
     */
    public void setMemberCardId(Integer memberCardId) {
        this.memberCardId = memberCardId;
    }
}