package vn.com.vti.springexam.entity;

public class Prefecture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.NAME
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.POPULATION
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    private Integer population;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.SECTION8_ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    private Integer section8Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.SECTION3_ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    private Integer section3Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture.IS_GOVERNMENT_DESIGNED_CITY
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    private Boolean isGovernmentDesignedCity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.ID
     *
     * @return the value of prefecture.ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.ID
     *
     * @param id the value for prefecture.ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.NAME
     *
     * @return the value of prefecture.NAME
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.NAME
     *
     * @param name the value for prefecture.NAME
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.POPULATION
     *
     * @return the value of prefecture.POPULATION
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public Integer getPopulation() {
        return population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.POPULATION
     *
     * @param population the value for prefecture.POPULATION
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public void setPopulation(Integer population) {
        this.population = population;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.SECTION8_ID
     *
     * @return the value of prefecture.SECTION8_ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public Integer getSection8Id() {
        return section8Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.SECTION8_ID
     *
     * @param section8Id the value for prefecture.SECTION8_ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public void setSection8Id(Integer section8Id) {
        this.section8Id = section8Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.SECTION3_ID
     *
     * @return the value of prefecture.SECTION3_ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public Integer getSection3Id() {
        return section3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.SECTION3_ID
     *
     * @param section3Id the value for prefecture.SECTION3_ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public void setSection3Id(Integer section3Id) {
        this.section3Id = section3Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture.IS_GOVERNMENT_DESIGNED_CITY
     *
     * @return the value of prefecture.IS_GOVERNMENT_DESIGNED_CITY
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public Boolean getIsGovernmentDesignedCity() {
        return isGovernmentDesignedCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture.IS_GOVERNMENT_DESIGNED_CITY
     *
     * @param isGovernmentDesignedCity the value for prefecture.IS_GOVERNMENT_DESIGNED_CITY
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public void setIsGovernmentDesignedCity(Boolean isGovernmentDesignedCity) {
        this.isGovernmentDesignedCity = isGovernmentDesignedCity;
    }
}