package vn.com.vti.springexam.entity;

public class PrefectureInfrastructure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture_infrastructure.ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture_infrastructure.INFRASTRUCTER_ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    private Integer infrastructerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prefecture_infrastructure.PREFECTURE_ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    private Integer prefectureId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture_infrastructure.ID
     *
     * @return the value of prefecture_infrastructure.ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture_infrastructure.ID
     *
     * @param id the value for prefecture_infrastructure.ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture_infrastructure.INFRASTRUCTER_ID
     *
     * @return the value of prefecture_infrastructure.INFRASTRUCTER_ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public Integer getInfrastructerId() {
        return infrastructerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture_infrastructure.INFRASTRUCTER_ID
     *
     * @param infrastructerId the value for prefecture_infrastructure.INFRASTRUCTER_ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public void setInfrastructerId(Integer infrastructerId) {
        this.infrastructerId = infrastructerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prefecture_infrastructure.PREFECTURE_ID
     *
     * @return the value of prefecture_infrastructure.PREFECTURE_ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public Integer getPrefectureId() {
        return prefectureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prefecture_infrastructure.PREFECTURE_ID
     *
     * @param prefectureId the value for prefecture_infrastructure.PREFECTURE_ID
     *
     * @mbg.generated Tue Sep 20 23:41:58 JST 2022
     */
    public void setPrefectureId(Integer prefectureId) {
        this.prefectureId = prefectureId;
    }
}